<?php
/**
 * PlatiOnline payment module
 *
 * @category    Xtreme
 * @package     Xtreme_PlatiOnline
 * @author      Marian-Daniel Ursache <marian.ursache@gmail.com>, Michael Mussulis <michael@xtreme-vision.net>
 * @copyright   Xtreme Vision SRL
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * Payment Failure template
 *
 * @var $block \Xtreme\PlatiOnline\Block\Payment\Failure
 */
?>
<br />
<p><?php echo __('Tranzactia a fost refuzata din unul dintre urmatoarele motive:')?></p>
<ul style="text-indent:10px">
<li><?php echo __('datele cardului au fost introduse incorect')?></li>
<li><?php echo __('nu exista fonduri suficiente in contul cardului')?></li>
<li><?php echo __('banca emitenta a refuzat tranzactia datorita unor restrictii de securitate impuse cardului sau tipul de card folosit nu este acceptat')?></li>
<li><?php echo __('reteaua de tranzactionare este momentan indisponibila')?></li>
</ul>
<?php if(!$this->getPOError()): ?>
    <p><?php echo __('Va recomandam sa reluati procesarea tranzactiei in cateva minute, dupa efectuarea schimbarilor necesare')?></p>
    <p><a href='<?php echo $this->getPaymentLink(); ?>' class='action primary'><?php echo __('REINCEARCA PLATA'); ?></a></p>
<?php endif; ?>
