<?php
/**
 * PlatiOnline payment module
 *
 * @category    Xtreme
 * @package     Xtreme_PlatiOnline
 * @author      Marian-Daniel Ursache <marian.ursache@gmail.com>, Michael Mussulis <michael@xtreme-vision.net>
 * @copyright   Xtreme Vision SRL
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * Payment Redirect template
 *
 * @var $block \Xtreme\PlatiOnline\Block\Payment\Redirect
 */
?>
You will be redirected shortly to the payment gateway. Please wait.
<br/>
<script type="text/javascript">
window.location = '<?php echo $this->getRedirectUrl(); ?>';
</script>
